# Generated by Django 5.2.10 on 2026-02-02 05:39

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('customer', 'Customer / End User'), ('editor', 'Editor'), ('chielf_editor', 'Chief Editor')], default='customer', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='brief description about the user')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='%y/%m/%d')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PK')),
                ('wetsite', models.URLField(blank=True)),
                ('is_varified', models.BooleanField(default=False, help_text='Editor verification status')),
                ('specialization', models.CharField(blank=True, help_text="Editor's area of expetise", max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
