# Generated by Django 5.2.10 on 2026-02-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='summery',
            field=models.TextField(blank=True, help_text='Brief summery of story', max_length=1000),
        ),
    ]
