# Generated by Django 5.2.10 on 2026-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='summery_image',
            field=models.ImageField(blank=True, null=True, upload_to='summries/%Y/%m/%d'),
        ),
    ]
